merged code from staging

diff --git a/auto-mx b/auto-mx
--- a/auto-mx
+++ b/auto-mx
@@ -1,36 +1,33 @@
-#!/bin/bash -e
+#!/bin/bash
 #
 # Mendix Installer (auto-mx)
 # Utility to interactively install and setup
 # Mendix, as well rest of utility's which
 # are needed to run Mendix applications.
 
-# todo, refactor existing code
-# into functions
-
-step1(){
-
+# Service Settings (service_settings)
 app_servicename_func(){
+
 # Service Name
-echo -e "\n------------------------------------\n"
+echo -e "\n-----------------------------------------\n"
 read -p "Specify \"Service Name\", i.e (NewApp): " app_servicename
 }
 
-app_displayname_func(){
 # Display Name 
-echo -e "\n------------------------------------\n"
+app_displayname_func(){
+echo -e "\n-----------------------------------------\n"
 read -p "Specify \"Display Name\", i.e (NewApp): " app_displayname
 }
 
-app_description_func(){
 # Description:  
-echo -e "\n------------------------------------\n"
+app_description_func(){
+echo -e "\n-----------------------------------------\n"
 read -p "Specify \"Description\": " app_description
 }
 
-app_startup_func(){
 # Startup Type
-echo -e "\n------------------------------------\n"
+app_startup_func(){
+echo -e "\n-----------------------------------------\n"
 echo -e "Start Mendix at boot?"
 read -p "[Y]es, [N]o, [S]kip: " app_startup
 
@@ -53,131 +50,254 @@ then
 	boot="No"
 	continue
 
-elif [[ "$letter" == [Nn]* ]]; 
+elif [[ "$letter" == [Ss]* ]]; 
 then
-	echo -e "\nMendix will not start at boot ..."
+	echo -e "\nSetting Mendix at boot, skipped ..."
 	boot="Option skip"
 	
 	continue
 
 else 
-	echo -e "\n--------------------------------\n"
+	echo -e "\n------------------------------------\n"
 	echo    "Non existing value: exiting ..."
-	echo -e "\n--------------------------------\n"
+	echo -e "\n------------------------------------\n"
 	
 	exit 1
 fi
 done
 }
 
-app_username_func(){
 # Username 
-echo -e "------------------------------------\n"
+app_username_func(){
+echo -e "-----------------------------------------\n"
 read -p "Specify \"User Name\": " app_username
 }
 
-app_password_func(){
-
 # Password 
-echo -e "\n------------------------------------\n"
+app_password_func(){
+echo -e "\n----------------------------------------\n"
 read -p "Specify \"User password\": " app_password
 }
 
-
-# calling step1 functions
-app_servicename_func
-app_displayname_func
-app_description_func
-app_startup_func
-app_username_func
-app_password_func
-
-
-echo -e "\n------------------------------------\n"
+spec(){
+echo -e "\n-----------------------------------------\n"
 echo -e "\nYou've specified following values:\n"
-echo -e "\n++++++++++++++++++++++++++++++++++++\n"
+echo -e "\n++++++++++++++++++++++++++++++++++++++++\n"
 echo -e "Service name: $app_servicename"
 echo -e "Display name: $app_displayname"
 echo -e "Description: $app_description"
 echo -e "Start at boot: $boot"
 echo -e "App. username: $app_username"
 echo -e "App. password: $app_password"
-echo -e "\n++++++++++++++++++++++++++++++++++++\n"
-
+echo -e "\n++++++++++++++++++++++++++++++++++++++++\n"
 }
 
-# Installer beginning
+# Installer started (install_start) 
+while [ install_start != "Q" ]
+do 
+clear
 
-echo -e "\n--------------------------------------\n"
-echo -e "Welcome to Mendix installer (auto-mx)"
+# Display menu
+echo -e "\n------------------------------------------\n"
+echo -e "Welcome to Mendix installer (auto-mx)\n"
 echo -e "\nPlease follow on-screen instructions"
-read -p "Continue? [Y]es, [N]o: " inst
+echo -e "\n------------------------------------------\n"
 
-for letter in "$inst"; do  
+echo -e "Continue?\n"
+echo "[Y]es"
+echo "[N]o"
+echo "[Q]uit"
 
-if [[ "$letter" == [Yy] ]]; 
-then
-
-# step1 call
-step1
-
-elif [[ "$letter" == [Nn]* ]]; 
-then
-	echo -e "\n--------------------------------------\n"	
-	echo -e "Quitting ...\n"
-	echo -e "Run \"auto-mx\" to start again"
-	echo -e "\n--------------------------------------\n"
+read -p ": " install_start
+	case $install_start in
 	
-	exit
+	Q|q)
+		echo "Goodbye!"
+		exit 1
+	;;
 
-else 
-	echo -e "\n--------------------------------\n"
-	echo -e "Non existing value: exiting ...\n"
-	echo -e "Run \"auto-mx\" to start again"	
-	echo -e "\n--------------------------------\n"
-	exit 1
-fi
+	Y|y)
+	# calling service_settings functions
+	app_servicename_func
+	app_displayname_func
+	app_description_func
+	app_startup_func
+	app_username_func
+	app_password_func
+
+	spec
+	break	
+	;;
+
+	N|n)
+		echo "Aborting installation"
+		exit 1
+	;;
+
+	*) 
+	echo "Non existing value"
+	;;
+	
+	esac
+
+	echo "press Enter for menu"
+	read key
 done
 
-# Step1 end dialog
-read -p "[N]ext Step, [E]dit Existing, [F]inish: " step1_end
+# Specify destinaton path (destination_path)
+destination_path(){
 
-for letter in "$step1_end"; do
+# Define custom path
+custom_appdest_func(){
+echo -e "-----------------------------------------\n"
+read -p "Specify \"custom app. destination\": " custom_appdest
+}
 
-if [[ "$letter" == [Nn] ]]; 
-then
-	echo -e "\nNeed to code this part (:\n"	
-	#continue
+while [ destination_path != "Q" ]
+do
+clear
 
-elif [[ "$letter" == [Ee]* ]]; 
-then
-	# todo
-	# add a call to individual functions
-	 
-	# call step1
-	step1
+# Specify destination path
+echo -e "\n------------------------------------------\n"
+echo -e "Specify location of apps and server files "
+echo -e "\n++++++++++++++++++++++++++++++++++++++++++\n"
+echo -e "\nWe recommend: /srv/mendix/$app_username"
+echo -e "\nto be your path.\n"
+echo -e "\n++++++++++++++++++++++++++++++++++++++++++\n"
 
-#	echo -e "\nWhat would you like to edit?\n"
-#	echo -e \"[1] Service Name\n"
-#	echo -e \"[2] Display Name\n"
-#	echo -e \"[3] Description\n"
-#	echo -e \"[4] Start at boot\n"
-#	echo -e \"[5] App. username\n"
-#	echo -e \"[6] App. password\n"
-#
-#	read -p "Enter option number: " step1_edit
+echo -e "[A]ccept and proceed\n"
+echo -e "[C]ustomize your own path"
+echo -e "[Q]uit"
 
-elif [[ "$letter" == [Ff]* ]]; 
-then
+read -p ": " destination_path
 
-	# Store variable somwhere ...
-	echo -e "\nNeed to code this part (:\n"
+    case $destination_path in
 
-else 
-	echo -e "\n--------------------------------\n"
-	echo    "Non existing value: exiting ..."
-	echo -e "\n--------------------------------\n"
-	
-	exit 1
-fi
+    A|a )
+    	path="/srv/mendix/$app_username"
+    	echo "$path"
+    	echo "movin on"
+    	break
+	;;
+
+    C|c )
+    	# todo
+    	# extend this!
+        read -p "Enter your own path: " path
+        echo "Specified path: $path"   
+        echo "Moving on"
+		break
+    ;;
+
+	Q|q)
+		echo "Aborting installation"
+		exit 1
+	;;
+
+	*) 
+	echo "Non existing value"
+	;;
+
+    esac
+    echo "press Enter for menu"
+	read key
 done
+}
+
+# Confirm Service Settings
+while [ service_settings_confrim != "Q" ]
+do 
+clear
+
+spec
+
+echo "[N]ext Step, [E]edit Existing, [F]inish: "
+
+read -p ": " service_settings_confrim
+	case $service_settings_confrim in 
+
+	Q|q)
+		echo "Goodbye!"
+		exit
+	;;
+
+	N|n)
+		echo "Moving to next step"
+		# Jump to the next step
+		destination_path
+		break
+	;;
+	
+	E|e)
+		spec
+	
+		echo -e "\nWhat would you like to edit?\n"
+		echo "[1] Service Name"
+		echo "[2] Display Name"
+		echo "[3] Description"
+		echo "[4] Start at boot"
+		echo "[5] App. username"
+		echo "[6] App. password"
+	
+	read -p "Enter option number: " service_settings_edit
+
+	for letter in "$service_settings_edit"; do
+
+	if [[ "$letter" == [1] ]]; 
+	then
+		app_servicename_func
+		spec
+
+	elif [[ "$letter" == [2] ]]; 
+	then
+		app_displayname_func
+		spec
+
+	elif [[ "$letter" == [3] ]]; 
+	then
+		app_description_func
+		spec
+
+	elif [[ "$letter" == [4] ]]; 
+	then
+		app_startup_func
+		spec
+
+	elif [[ "$letter" == [5] ]]; 
+	then
+		app_username_func
+		spec
+	
+	elif [[ "$letter" == [6] ]]; 
+	then
+		app_password_func
+		spec
+	elif [[ "$letter" == [Ff] ]]; 
+	then
+		echo "finishing"
+		break
+
+	else
+		echo "Seriously?"
+		# exit | exit 1			
+
+	fi
+	done
+	;;
+
+	F|f)
+		echo "my work is done here"
+		break
+	;;
+
+	*) 
+	echo "Non existing value"
+	;;
+	
+	esac
+
+	echo "press Enter for menu"
+	read key
+done
+
+exit 0
